### ISSUE TITLE
PostgreSQL table generation double single quotes issue

### ISSUE THREAD

**Issue by r-work** [martinjw/dbschemareader#145]
If column default value is `('0.0.0.0')` when calling TableGenerator.Write default value will be written like `''0.0.0.0''`.

Maybe [this line](https://github.com/martinjw/dbschemareader/blob/8fc56372b4817f741da34711fdb5df8793831b06/DatabaseSchemaReader/SqlGen/PostgreSql/TableGenerator.cs#L173) might be the cause of it? Should probably check to see if default value is already surrounded by single quotes.

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.7.14.0

**Comment by r-work** [comment]
I have `2.7.14.0` and still have the same issue.
In the releases page it indicates that this was fixed in `2.7.15.0` which the package doesn't seem available.
